### ISSUE TITLE
Support generated columns

### ISSUE THREAD

**Issue by arnaud** [motor-admin/motor-admin#17] opened 2021-11-14 19:01 UTC
A table with generated columns currently prevents the admin panel from creating new entries:

> PG::SyntaxError: **ERROR:** cannot insert into column `"full_text"` DETAIL: Column `"full_text"` is a generated column.

**Comment by omohokcoj** [comment] 2021-11-14 19:13
@arnaud did you try to mark generated column as read-only via column settings in motor admin?
It should solve the issue but I agree that those columns should be marked as read-only by default.
There will be a fix released for that in the new version.

**Comment by arnaud** [comment] 2021-11-14 19:15
Neither visibility (`readonly`, `hidden`) options actually worked.

**Comment by omohokcoj** [comment] 2021-11-15 13:12
@arnaud I was not able to reproduce this - it's possible to create new records with generated columns even when they are read-write - it also works with read-only hidden access type.
Can you provide the actual SQL of your table/generated column - maybe it will help to reproduce the issue.

**Comment by arnaud** [comment] 2021-11-15 23:27
You should be able to reproduce the issue with such a generated `full_name` column like this one:

```sql
CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  email CITEXT UNIQUE NOT NULL,
  encrypted_password TEXT NOT NULL,
  first_name TEXT,
  last_name TEXT,
  --             👇 this field is computed automatically
  full_name TEXT GENERATED ALWAYS AS (COALESCE(first_name, '') || ' ' || COALESCE(last_name, '')) STORED,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
```

**Comment by omohokcoj** [comment] 2021-11-16 14:11
@arnaud  it has been fixed in the newest version.
You can learn about how to upgrade to the latest version here:
https://github.com/motor-admin/motor-admin/releases/tag/latest

**Closed** 2021-11-21 15:39 UTC
Labels: bug
