### ISSUE TITLE
Email alerts not working when clicking "send now"

### ISSUE THREAD

**Issue by avimar** [motor-admin/motor-admin#3] opened 2021-11-03 21:34 UTC
I'm running under docker on windows with wsl2 -- Docker version 20.10.8, build 3967b7d

I added Amazon SES SMTP credentials (that I'm pretty sure are active)

1) I ticked "send even if empty" and hit save, and then hit send now.

2) I created a new alert for something that definitely has data, and I'm getting:

This error (in the web and in docker logs)
`Please specify your sender address via MOTOR_ALERTS_FROM_ADDRESS environment variable`

But I set a from address when I set the SMTP information.

3) I restarted docker setting that variable and now I get:

```
E, [2021-11-03T21:31:55.174745 #1] ERROR -- : [be0b97a4-2f1c-4bad-a640-f65b2c685e7a] end of file reached
E, [2021-11-03T21:31:55.174820 #1] ERROR -- : [be0b97a4-2f1c-4bad-a640-f65b2c685e7a] /__enclose_io_memfs__/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:944:in `recv_response'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:553:in `block in do_start'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:954:in `critical'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:553:in `do_start'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:518:in `start'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:276:in `deliver!'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionmailer-7.0.0.alpha2/lib/action_mailer/message_delivery.rb:109:in `block in deliver_now!'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionmailer-7.0.0.alpha2/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionmailer-7.0.0.alpha2/lib/action_mailer/message_delivery.rb:108:in `deliver_now!'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/motor-admin-0.2.18/app/controllers/motor/send_alerts_controller.rb:11:in `create'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/abstract_controller/base.rb:214:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/rendering.rb:53:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/abstract_controller/callbacks.rb:221:in `block in process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/audited-5.0.2/lib/audited/sweeper.rb:16:in `around'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/audited-5.0.2/lib/audited/sweeper.rb:16:in `around'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:138:in `run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/abstract_controller/callbacks.rb:220:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/instrumentation.rb:65:in `block in process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/notifications.rb:207:in `block in instrument'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/notifications.rb:207:in `instrument'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/instrumentation.rb:64:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.alpha2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/abstract_controller/base.rb:151:in `process'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal.rb:188:in `dispatch'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal.rb:251:in `dispatch'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:32:in `each'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:32:in `serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/route_set.rb:845:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:530:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/railtie.rb:207:in `public_send'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/railtie.rb:207:in `method_missing'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:32:in `each'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:32:in `serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/route_set.rb:845:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/cookies.rb:693:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:99:in `run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/rack/logger.rb:25:in `block in call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/tagged_logging.rb:37:in `tagged'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/tagged_logging.rb:99:in `tagged'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/rack/logger.rb:25:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/static.rb:24:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/host_authorization.rb:90:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:530:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/configuration.rb:249:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/request.rb:77:in `block in handle_request'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/request.rb:76:in `handle_request'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/server.rb:447:in `process_client'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
I, [2021-11-03T21:31:55.175263 #1]  INFO -- : [be0b97a4-2f1c-4bad-a640-f65b2c685e7a] {"method":"POST","path":"/api/send_alerts","status":500,"duration":32053.6,"view":0.16,"db":452.22,"fwd":"172.17.0.1","uid":1}E, [2021-11-03T21:32:52.180681 #1] ERROR -- : [b9583da1-0c3c-4510-8662-f310f5b8bfa6] end of file reached
E, [2021-11-03T21:32:52.180757 #1] ERROR -- : [b9583da1-0c3c-4510-8662-f310f5b8bfa6] /__enclose_io_memfs__/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:944:in `recv_response'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:553:in `block in do_start'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:954:in `critical'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:553:in `do_start'
/__enclose_io_memfs__/lib/ruby/2.7.0/net/smtp.rb:518:in `start'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/mail-2.7.1/lib/mail/message.rb:276:in `deliver!'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionmailer-7.0.0.alpha2/lib/action_mailer/message_delivery.rb:109:in `block in deliver_now!'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionmailer-7.0.0.alpha2/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionmailer-7.0.0.alpha2/lib/action_mailer/message_delivery.rb:108:in `deliver_now!'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/motor-admin-0.2.18/app/controllers/motor/send_alerts_controller.rb:11:in `create'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/abstract_controller/base.rb:214:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/rendering.rb:53:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/abstract_controller/callbacks.rb:221:in `block in process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:118:in `block in run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/audited-5.0.2/lib/audited/sweeper.rb:16:in `around'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/audited-5.0.2/lib/audited/sweeper.rb:16:in `around'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:127:in `block in run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:138:in `run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/abstract_controller/callbacks.rb:220:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/instrumentation.rb:65:in `block in process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/notifications.rb:207:in `block in instrument'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/notifications.rb:207:in `instrument'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/instrumentation.rb:64:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activerecord-7.0.0.alpha2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/abstract_controller/base.rb:151:in `process'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal.rb:188:in `dispatch'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_controller/metal.rb:251:in `dispatch'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:32:in `each'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:32:in `serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/route_set.rb:845:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:530:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/railtie.rb:207:in `public_send'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/railtie.rb:207:in `method_missing'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:32:in `each'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/journey/router.rb:32:in `serve'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/routing/route_set.rb:845:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/http/permissions_policy.rb:22:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/cookies.rb:693:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/callbacks.rb:99:in `run_callbacks'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/rack/logger.rb:25:in `block in call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/tagged_logging.rb:37:in `tagged'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/activesupport-7.0.0.alpha2/lib/active_support/tagged_logging.rb:99:in `tagged'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/rack/logger.rb:25:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/request_id.rb:26:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/static.rb:24:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/actionpack-7.0.0.alpha2/lib/action_dispatch/middleware/host_authorization.rb:90:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/railties-7.0.0.alpha2/lib/rails/engine.rb:530:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/configuration.rb:249:in `call'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/request.rb:77:in `block in handle_request'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/request.rb:76:in `handle_request'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/server.rb:447:in `process_client'
/__enclose_io_memfs__/lib/ruby/gems/2.7.0/gems/puma-5.5.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by omohokcoj** [comment] 2021-11-04 13:18
@avimar thanks for reporting the bug with ENV variable - it will be fixed in the new version.

Unfortunately, I was not able to reproduce that "end of file reached" error - SES works in docker and sends emails without any issues - it looks like some network error - maybe you made a typo in SES credentials?
Also maybe your IPS doesn't allow sending requests to 587 port (SMTP port) - you might need to try sending it from some cloud vps.

Here is how my SES credentials look like:
![image](https://user-images.githubusercontent.com/5418788/140319723-0d8523ca-83cb-494b-bc7a-308d4b50a9b6.png)

**Comment by avimar** [comment] 2021-11-10 16:37
My credentials look similar. I tried switching the port to 587 (I was using 465?)

I only get "Alert email has been sent!" and nothing bad up in the logs but I don't get any email, not even in spam.

Logs show:
```
I, [2021-11-10T16:34:07.600894 #1]  INFO -- : [25c8e824-cda0-4232-b96e-6887007332db] {"method":"POST","path":"/api/send_alerts","status":200,"duration":430.96,"view":0.0,"db":344.64,"fwd":"172.17.0.1","uid":1}
```

How would I go about debugging the SMTP?

**Comment by omohokcoj** [comment] 2021-11-10 16:46
@avimar I think you should try to send an email using your credentials via some other method to see if your SES credentials/configurations work - you can try to do it with curl:
https://www.reddit.com/r/aws/comments/ibx1jc/sending_with_ses_using_curl_in_a_bash_script/
The email could have been accepted on SES SMTP (so there were no errors in the log) but not delivered because of your account limitations/configurations (sandbox/unconfirmed received).

**Comment by avimar** [comment] 2021-11-10 18:32
I used that script with the same SMTP credentials and it worked -- email received. (but only with my original port 465 and not 587)

I re-copied the credentials, port, host into motor-admin and again it just says "sent" without any errors.

**Comment by omohokcoj** [comment] 2021-11-11 14:22
@avimar thanks, it helped to investigate the issue.
It's fixed now in the latest version.
You can learn about how to upgrade to the latest version here:
https://github.com/motor-admin/motor-admin/releases/tag/latest

**Comment by avimar** [comment] 2021-11-11 18:31
Thanks, it worked for an alert with data!

But if there's no data, it still seems to be unexpected behavior:

1) I have an alert
2) I saved "send empty? CHECKED"
3) Click "Send now"

I get "Alert email has been sent!" but I didn't get anything.
I expected it would be running the same code path and would indeed send me the empty alert, like it would on a cron.

It could be altered to return "no results, no email sent" but as currently it's misleading.

Thanks!

**Comment by omohokcoj** [comment] 2021-11-11 18:36
Thanks, @avimar it makes sense - it will be fixed in the future release.
Closing this issue for now since the email issue with SMTP has been resolved.

**Closed by omohokcoj** 2021-11-11 18:36 UTC

**Comment by avimar** [comment] 2021-11-11 19:07
Amazing, thanks!
