### ISSUE TITLE
Core Dumped in Docker 

### ISSUE THREAD

**Issue by carlozleite** [motor-admin/motor-admin#41] opened 2022-03-17 15:30 UTC
I try to start the container but it crashes immediately, the console output is this:

```Assertion Failed: /tmp/rubyc/ruby-3.1.0.dev/vm_insnhelper.c:5719:Init_vm_stack_canary:n == 0
ruby 3.1.0p0 (2021-12-25) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0001 p:0000 s:0003 E:001be0 (none) [FINISH]


-- C level backtrace information -------------------------------------------
/app/motor-admin(rb_print_backtrace+0x14) [0x7badaa] /tmp/rubyc/ruby-3.1.0.dev/vm_dump.c:759
/app/motor-admin(rb_vm_bugreport) /tmp/rubyc/ruby-3.1.0.dev/vm_dump.c:1045
/app/motor-admin(rb_assert_failure+0x76) [0x62545f] /tmp/rubyc/ruby-3.1.0.dev/error.c:885
/app/motor-admin(rb_vm_canary_is_found_dead+0x0) [0x78812f] /tmp/rubyc/ruby-3.1.0.dev/vm_insnhelper.c:5719
/app/motor-admin(Init_vm_stack_canary) (null):0
/app/motor-admin(rb_call_inits+0x10a) [0x6591c2] /tmp/rubyc/ruby-3.1.0.dev/inits.c:77
/app/motor-admin(ruby_setup+0x165) [0x62b498] /tmp/rubyc/ruby-3.1.0.dev/eval.c:88
/app/motor-admin(ruby_init+0x6) [0x62b563] /tmp/rubyc/ruby-3.1.0.dev/eval.c:100
/app/motor-admin(main+0x227) [0x48330f] /tmp/rubyc/ruby-3.1.0.dev/main.c:154

-- Other runtime information -----------------------------------------------

* Loaded script: ruby

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 fiber.so
    3 rational.so
    4 complex.so
    5 ruby2_keywords.rb

* Process memory map:

00400000-00ea3000 r-xp 00000000 fd:06 100730224                          /app/motor-admin
00ea3000-00eec000 r-xp 00aa2000 fd:06 100730224                          /app/motor-admin
00eec000-04245000 rwxp 00aeb000 fd:06 100730224                          /app/motor-admin
04245000-04264000 rwxp 00000000 00:00 0
04396000-043b7000 rwxp 00000000 00:00 0                                  [heap]
043b7000-0447e000 rwxp 00000000 00:00 0                                  [heap]
7f010e562000-7f010e752000 r-xs 00000000 fd:03 3130003                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f010e752000-7f010f829000 rwxp 00000000 00:00 0
7f010f829000-7f011406d000 r-xs 00000000 fd:06 100730224                  /app/motor-admin
7f011406d000-7f0114086000 r-xp 00000000 fd:03 3130028                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f0114086000-7f0114087000 r-xp 00018000 fd:03 3130028                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f0114087000-7f0114088000 rwxp 00019000 fd:03 3130028                    /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
7f0114088000-7f0114089000 ---p 00000000 00:00 0
7f0114089000-7f011412a000 rwxp 00000000 00:00 0
7f011412a000-7f011412b000 ---p 00000000 00:00 0
7f011412b000-7f01141cc000 rwxp 00000000 00:00 0
7f01141cc000-7f01141cd000 ---p 00000000 00:00 0
7f01141cd000-7f011426e000 rwxp 00000000 00:00 0
7f011426e000-7f011426f000 ---p 00000000 00:00 0
7f011426f000-7f0114310000 rwxp 00000000 00:00 0
7f0114310000-7f0114311000 ---p 00000000 00:00 0
7f0114311000-7f01143b2000 rwxp 00000000 00:00 0
7f01143b2000-7f01143b3000 ---p 00000000 00:00 0
7f01143b3000-7f0114454000 rwxp 00000000 00:00 0
7f0114454000-7f0114455000 ---p 00000000 00:00 0
7f0114455000-7f01144f6000 rwxp 00000000 00:00 0
7f01144f6000-7f01144f7000 ---p 00000000 00:00 0
7f01144f7000-7f0114598000 rwxp 00000000 00:00 0
7f0114598000-7f0114599000 ---p 00000000 00:00 0
7f0114599000-7f011463a000 rwxp 00000000 00:00 0
7f011463a000-7f011463b000 ---p 00000000 00:00 0
7f011463b000-7f01146dc000 rwxp 00000000 00:00 0
7f01146dc000-7f01146dd000 ---p 00000000 00:00 0
7f01146dd000-7f011477e000 rwxp 00000000 00:00 0
7f011477e000-7f011477f000 ---p 00000000 00:00 0
7f011477f000-7f0114820000 rwxp 00000000 00:00 0
7f0114820000-7f0114821000 ---p 00000000 00:00 0
7f0114821000-7f01148c2000 rwxp 00000000 00:00 0
7f01148c2000-7f01148c3000 ---p 00000000 00:00 0
7f01148c3000-7f0114964000 rwxp 00000000 00:00 0
7f0114964000-7f0114965000 ---p 00000000 00:00 0
7f0114965000-7f0114a06000 rwxp 00000000 00:00 0
7f0114a06000-7f0114a07000 ---p 00000000 00:00 0
7f0114a07000-7f0114aa8000 rwxp 00000000 00:00 0
7f0114aa8000-7f0114aa9000 ---p 00000000 00:00 0
7f0114aa9000-7f0114b4a000 rwxp 00000000 00:00 0
7f0114b4a000-7f0114b4b000 ---p 00000000 00:00 0
7f0114b4b000-7f0114bec000 rwxp 00000000 00:00 0
7f0114bec000-7f0114bed000 ---p 00000000 00:00 0
7f0114bed000-7f0114c8e000 rwxp 00000000 00:00 0
7f0114c8e000-7f0114c8f000 ---p 00000000 00:00 0
7f0114c8f000-7f0114d30000 rwxp 00000000 00:00 0
7f0114d30000-7f0114d31000 ---p 00000000 00:00 0
7f0114d31000-7f0114dd2000 rwxp 00000000 00:00 0
7f0114dd2000-7f0114dd3000 ---p 00000000 00:00 0
7f0114dd3000-7f0114e74000 rwxp 00000000 00:00 0
7f0114e74000-7f0114e75000 ---p 00000000 00:00 0
7f0114e75000-7f0114f16000 rwxp 00000000 00:00 0
7f0114f16000-7f0114f17000 ---p 00000000 00:00 0
7f0114f17000-7f0114fb8000 rwxp 00000000 00:00 0
7f0114fb8000-7f0114fb9000 ---p 00000000 00:00 0
7f0114fb9000-7f011505a000 rwxp 00000000 00:00 0
7f011505a000-7f011505b000 ---p 00000000 00:00 0
7f011505b000-7f01150fc000 rwxp 00000000 00:00 0
7f01150fc000-7f01150fd000 ---p 00000000 00:00 0
7f01150fd000-7f011519e000 rwxp 00000000 00:00 0
7f011519e000-7f011519f000 ---p 00000000 00:00 0
7f011519f000-7f0115240000 rwxp 00000000 00:00 0
7f0115240000-7f0115241000 ---p 00000000 00:00 0
7f0115241000-7f01152e2000 rwxp 00000000 00:00 0
7f01152e2000-7f01152e3000 ---p 00000000 00:00 0
7f01152e3000-7f0115384000 rwxp 00000000 00:00 0
7f0115384000-7f0115385000 ---p 00000000 00:00 0
7f0115385000-7f0115426000 rwxp 00000000 00:00 0
7f0115426000-7f0115427000 ---p 00000000 00:00 0
7f0115427000-7f01174c8000 rwxp 00000000 00:00 0
7f01174cb000-7f011758c000 rwxp 00000000 00:00 0
7f011758d000-7f011768e000 rwxp 00000000 00:00 0
7f011768e000-7f0117691000 rwxp 00000000 00:00 0
7f0117691000-7f0117878000 r-xp 00000000 fd:03 3130003                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f0117878000-7f0117879000 ---p 001e7000 fd:03 3130003                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f0117879000-7f011787c000 r-xp 001e7000 fd:03 3130003                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f011787c000-7f011787f000 rwxp 001ea000 fd:03 3130003                    /usr/lib/x86_64-linux-gnu/libc-2.31.so
7f011787f000-7f0117885000 rwxp 00000000 00:00 0
7f0117885000-7f0117888000 r-xp 00000000 fd:03 3130128                    /usr/lib/x86_64-linux-gnu/libutil-2.31.so
7f0117888000-7f0117889000 r-xp 00002000 fd:03 3130128                    /usr/lib/x86_64-linux-gnu/libutil-2.31.so
7f0117889000-7f011788a000 rwxp 00003000 fd:03 3130128                    /usr/lib/x86_64-linux-gnu/libutil-2.31.so
7f011788a000-7f01179d7000 r-xp 00000000 fd:03 3130045                    /usr/lib/x86_64-linux-gnu/libm-2.31.so
7f01179d7000-7f01179d8000 r-xp 0014c000 fd:03 3130045                    /usr/lib/x86_64-linux-gnu/libm-2.31.so
7f01179d8000-7f01179d9000 rwxp 0014d000 fd:03 3130045                    /usr/lib/x86_64-linux-gnu/libm-2.31.so
7f01179d9000-7f0117a0a000 r-xp 00000000 fd:03 3130010                    /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f0117a0a000-7f0117a0b000 r-xp 00030000 fd:03 3130010                    /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f0117a0b000-7f0117a0c000 rwxp 00031000 fd:03 3130010                    /usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0
7f0117a0c000-7f0117a14000 rwxp 00000000 00:00 0
7f0117a14000-7f0117a18000 r-xp 00000000 fd:03 3130014                    /usr/lib/x86_64-linux-gnu/libdl-2.31.so
7f0117a18000-7f0117a19000 r-xp 00003000 fd:03 3130014                    /usr/lib/x86_64-linux-gnu/libdl-2.31.so
7f0117a19000-7f0117a1a000 rwxp 00004000 fd:03 3130014                    /usr/lib/x86_64-linux-gnu/libdl-2.31.so
7f0117a1a000-7f0117a22000 r-xp 00000000 fd:03 3130101                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f0117a22000-7f0117a23000 ---p 00008000 fd:03 3130101                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f0117a23000-7f0117a24000 r-xp 00008000 fd:03 3130101                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f0117a24000-7f0117a25000 rwxp 00009000 fd:03 3130101                    /usr/lib/x86_64-linux-gnu/librt-2.31.so
7f0117a25000-7f0117a42000 r-xp 00000000 fd:03 3130097                    /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f0117a42000-7f0117a43000 r-xp 0001c000 fd:03 3130097                    /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f0117a43000-7f0117a44000 rwxp 0001d000 fd:03 3130097                    /usr/lib/x86_64-linux-gnu/libpthread-2.31.so
7f0117a44000-7f0117a4a000 rwxp 00000000 00:00 0
7f0117a4d000-7f0117a79000 r-xp 00000000 fd:03 3127581                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f0117a7a000-7f0117a7b000 r-xp 0002c000 fd:03 3127581                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f0117a7b000-7f0117a7c000 rwxp 0002d000 fd:03 3127581                    /usr/lib/x86_64-linux-gnu/ld-2.31.so
7f0117a7c000-7f0117a7d000 rwxp 00000000 00:00 0
7ffef9c95000-7ffefa494000 rwxp 00000000 00:00 0                          [stack]
7ffefa4e2000-7ffefa4e4000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


Aborted (core dumped)```

**Comment by omohokcoj** [comment] 2022-04-13 17:14
@carlozleite unfortunately i was not able to reproduce this issue.
closing it for now - please reopen if you can provide more details regarding how to reproduce this issue.

**Closed by omohokcoj** 2022-04-13 17:14 UTC
