### ISSUE TITLE
PostgreSQL specify schemas, or excluding schemas

### ISSUE THREAD

**Issue by nodesocket** [motor-admin/motor-admin#4] opened 2021-11-04 23:26 UTC
Using PostgreSQL and PostGIS and it's pulling in all the `tiger`, `tiger_data`, `topology` schemas and data. How can I specify only the schemas I wish to use within Motor Admin. Alternatively, a way to specify schemas I wish to exclude from Motor Admin.

Related, I think I hit some sort of limit in Motor Admin, because I only see data from the PostGIS schemas. I don't see my schema tables even listed at all.

**Comment by omohokcoj** [comment] 2021-11-05 09:12
@nodesocket thanks for reporting this - it seems like motor admin only builds admin UI using tables from the default "public" pg schema and this schema contains only tiger, tiger_data, topology tables, and all your other application data is stored in some other custom schema.

I'll investigate this issue - there should be a simple solution for this use case - will let you know once it's released in the new version.

**Comment by omohokcoj** [comment] 2021-11-06 14:20
@nodesocket now Motor Admin uses all pg scheme/tables to build resources UI on top of them.
You need to update to the latest 0.2.19 version - hope it solves the issue.

**Comment by nodesocket** [comment] 2021-11-07 19:11
@omohokcoj thanks. I was able to run the latest version in emulation (Rosetta), but still with all the PostGIS data, tables, and functions **there is a lot of noise**. Is there anyway to get a feature to select/limit the schemas I want to import into Motor Admin?

**Comment by omohokcoj** [comment] 2021-11-07 19:13
@nodesocket you can hide resources (aka tables) via settings:
https://www.youtube.com/watch?v=ngVoci8Hll4

**Comment by omohokcoj** [comment] 2021-11-15 12:54
Closing this - it's possible to remove table/resources via settings UI. Please feel free to reopen if needed.

**Closed by omohokcoj** 2021-11-15 12:55 UTC

**Comment by irisjae** [comment] 2021-12-11 12:27
I have not managed to get the schema feature working. No matter what I input in the schema, it seems that only my table from the public schema are getting pulled. On version 0.2.33 here. Any idea what could be the issue?

**Comment by omohokcoj** [comment] 2021-12-11 13:54
@irisjae are you sure that the postgres role you're using to authenticate motor admin is allowed to read from those custom schemas? Maybe the issue is caused by pg roles/permissions - Motor Admin loads table from all available schemas by default without any additional configurations.

**Comment by irisjae** [comment] 2021-12-11 14:43
@omohokcoj Yes, I'm fairly certain. I've even tried creating a role which does not have access to the public schema and only has access to the schema in question. For the time being I've resorted to rearranging my schema structure. If it keeps bothering me I'll try to get a reproducible example for you. Thanks!

**Comment by omohokcoj** [comment] 2021-12-11 14:46
thanks @irisjae unfortunately I'm not able to reproduce this issue.
try to run `select schemaname, tablename from pg_tables where schemaname NOT IN ('pg_catalog', 'information_schema')` Motor admin uses this query to fetch table names from all schemas - that would be interesting to see if the missing tables/schemas are returned by the query.
